### ISSUE TITLE
Columns within households and recipients table must be added for API to function

### ISSUE THREAD

**Issue by LoganTilley** [Lambda-School-Labs/family-promise-service-tracker-be-a#114]
**Note:** There is a near copy of this issue on the DS API, as this issue directly involves both repositories. 

## recipients

- has_disability: bool
- has_valid_ssi: bool
- has_valid_medicare_card

## households

- is_unstable

Details for each of these can be found within the Trello board under **KnownDefects.md DS**. These must be added for the DS API eligibility endpoint to function. Feel free to help the DS team get started with `knex` if they're interested in undertaking this side of the workload.

**Comment by santorap** [comment]
This issue was resolved with [PR118](https://github.com/Lambda-School-Labs/family-promise-service-tracker-be-a/pull/118).
