### ISSUE TITLE
Docker setup for Windows doesn't work properly, easy workaround exists

### ISSUE THREAD

**Issue by LoganTilley** [Lambda-School-Labs/family-promise-service-tracker-be-a#115]
When setting up the database on Windows using the provided instructions for Docker, api-dev is not created. You must log into pgadmin through the localhost after running the setup and add api-dev manually before continuing with the `npm` instructions. api-test doesn't seem to be necessary currently. The issue seems to be with Unix commands being run through command prompt, even when it's started through a Unix terminal like Git Bash. Perhaps setting Git Bash as the default terminal would resolve this, but it shouldn't be necessary.

**Comment by ahmedseragcodes** [comment]
Ran into this issue on windows and resolved alongside Logan. Basically API-DEV was the name of the server, that was already created, but api-dev as the name of a database did not exist yet. Just right click databases under API-DEV server, create database named api-dev (lowercase), then re-run migration command in VS Code terminal and you should be good to go.
